name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    name: Setup Environment and build
    runs-on: self-hosted
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate app bundle
        run: ./gradlew app:bundleRelease --stacktrace

      - name: Sign app bundle
        run: |
          jarsigner -keystore app/*.jks \
          -storepass ${{ secrets.KEY_STORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/bundle/release/app-release.aab ${{ secrets.ALIAS }}

    #   STEP 2 : Upload the Artifact
#    upload:
#      needs: [ build ]
#      name: Upload the signed artifact
#      runs-on: self-hosted
      steps:
        - name: Upload Bundle
          uses: actions/upload-artifact@v2
          with:
            name: signed_app_bundle
            path: app/app-release.aab


    # Step 3 : Release to playstore
